# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19981b9fcee0a9e368d60960870627919a7ab8fdcdee0244796cb9d9808d465319b21c2357ee1824e534e2ba0d42eb99ad53aa9baf6beaa4d23750305be92109

test:
  secret_key_base: 3b115a02f7fbcf5bfd611c3459efda88e1257ca3c9875635db8783904431ebf96f1b2f980287477ec10c1b4971642dc9f1ab57ce1ad4c6b2b5012a17efce2cbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
